sudo: required

language: go

services:
  - docker

jobs:
  include:
    - stage: Integration and Unit Tests
      script:  go test -v ./imagediff/
    - stage: Deploy
      deploy:
        - provider: script
          script: travis/docker-push.sh latest
          skip_cleanup: true
          on:
            branch: master
        - provider: script
          script: travis/docker-push.sh $TRAVIS_TAG
          skip_cleanup: true
          on:
            tags: true