sudo: required

language: go

services:
  - docker


jobs:
  include:
    - stage: Integration and Unit Tests
      script:  go test -v ./imagediff/
    - stage: Build and push docker when tag is set
      script: travis/docker-push.sh $TRAVIS_TAG
      on: tags: true     

branches:
  only:
    - master